apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  google_api_key: Z29vZ2xlLWFwaS1rZXk=  # "google-api-key" (base64)
  aws_access_key: QUJDNDEyMzQ1Njc4OQ==  # "ABC4123456789" (base64)
  jwt_secret: c2VjcmV0LXRva2Vu  # "secret-token" (base64)
